package c
const (
	BASE = 0
	QUOTE = 1
	MIN_PERC_DIFF = 0.1
	MAX_PERC_DIFF = 30
	//POOL_CHECK_MS = 30 * 1000
	ALLPOOL_CHECK_MS = 5 * 1000
	DEX_API_RATE_SLEEP_MS = 500
	RESUBSCRIBE_DEPTH_SEC = 10
	BDEX_ORDERBOOK_CHECK_MS = 100 * 1000
	BINANCE_ORDERBOOK_CHECK_MS = 100 * 1000
	TCPOOL_ORDERBOOK_CHECK_MS = 100 * 1000 // 100 sec
	BINANCE_GETSERVICE_ERR_SLEEP_MS = 400
	BINANCE_GETSERVICE_ERR_SLEEP_TRY_CNT = 5
	ORDER_RESULT_WAIT_CNT = 10
	ORDER_RESULT_CHECK_SEC = 1
	BNB_SEND_TOKEN_INV_SEQ_TRY_CNT = 10
	WAIT_AFTER_ZERO_WALLET_SEC = 1
	MIN_SWAP_RUNE = 3

	MAX_ARB_RUNE = 1000
	MIN_RUNE_YIELD = 1
	MIN_RUNE_ARB_AMOUNT = 4

	BINANCE_LIMIT_ORDER_FEE = 0.001 // not used - BNB fees
	BDEX_LIMIT_ORDER_FEE = 0.001

	BNB_TX_FEE = 0.000375

	THOR_API_RATE_LIMIT_MS = 100

	DO_BALANCE_MIN_DIFF_PERC = 30
	DO_BALANCE_MIN_AMOUNT_RUNE = 30

	WALLET_CHECK_SEC = 60
)
var (
	CHAIN_SENDING_PREFERENCE = [4]string{"BNB", "BSC", "THOR", "ETH"}
)